name: 'aws-secrets-manager-actions'
description: 'GitHub Actions for AWS Secrets Manager'
inputs:
  SECRET_NAME:
    description: 'Set secret name that you want to get.'
    required: true
  AWS_REGION:
    description: 'Set AWS region'
    required: true
  OUTPUT_PATH:
    description: 'Set output file where variables are write'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'lock'
  color: 'orange'
